### PR TITLE
added two new sections- 1) Mood  2) Popular new releases

### PR DESCRIPTION
**Pull request by dheeraj-singh-github**

### CODE REVIEW

**Comment by dheeraj-singh-github** [comment]
@TaufeeqRiyaz i have added two new sections. kindly check and label this PR with hactoberfest and hactoberfest-accepted

**Comment by dheeraj-singh-github** [comment]
@TaufeeqRiyaz 
image

**Comment by 0xtaufeeq** [comment]
Merged, thank you for contributing, leave a star to support the repo :)

**Comment by dheeraj-singh-github** [comment]
@TaufeeqRiyaz thanks for merging the PR but in my hactoberfest account it is showing not accepted.

image
image

**Comment by 0xtaufeeq** [comment]
> @TaufeeqRiyaz thanks for merging the PR but in my hactoberfest account it is showing not accepted.
> 
> image
> image
> 
> 

it might take sometime to update. I request you to wait for some more time.

**Pull request merged**
