### PR TITLE
Here it is 

### PR DESCRIPTION
**Pull request by sauravsilawat**

### CODE REVIEW

**Comment by 0xtaufeeq** [comment]
merged, thank you for contributing! 
leave a star to support the repo 😄

**Comment by sauravsilawat** [comment]
Thank you

**Comment by sauravsilawat** [comment]
Wait, I opened your site on my smartphone and there is a problem with the play/pause bar. I will quickly fix it.

**Comment by 0xtaufeeq** [comment]
> Wait, I opened your site on my smartphone and there is a problem with the play/pause bar. I will quickly fix it.

Thank you very much, I've merged your pull request.

**Pull request merged**
